### ISSUE TITLE
Remove search box, or implement back end udaru search

### ISSUE THREAD

**Issue by dberesford** [nearform/udaru-ui-admin#7]
if the teams table is now paginated on server side, the search box is not going to find your team/user unless it's already loaded. Suggest removing it in the short term, but we should have a search api in the near future.

**Comment by jimmymintzer** [comment]
The search box was removed but I will leave this issue open to link to when search api is updated.

**Comment by dberesford** [comment]
Support being added to Udaru for search: https://github.com/nearform/udaru/issues/462

**Comment by jimmymintzer** [comment]
Resolved search for team with PR #10

**Comment by jimmymintzer** [comment]
Merged in code for team users search. It will need nearform/udaru#463 merged before it works correctly

cc @donovanh
